### PR TITLE
Drop exec, pause, resume, and signal

### PR DESCRIPTION
**Pull request by wking**
All of these require state information to be shared between funC
invocations (to map from a container ID to the
cgroups/namespaces/etc.), and after [today's meeting](http://ircbot.wl.linuxfoundation.org/meetings/opencontainers/2015/opencontainers.2015-12-02-18.01.html) we may be
[backing away from that](http://ircbot.wl.linuxfoundation.org/meetings/opencontainers/2015/opencontainers.2015-12-02-18.01.log.html#l-79).  Even if we keep a requirement for sharing state
between funC invocations, we don't want to specify these IPC-requiring
commands until we have more clarity on that requirement in the spec.

Pause, resume, and signal are [still in the current lifecycle pull
request](https://github.com/mrunalp/specs/commit/bd549a2c9569fd5d775323f7f39c835baf825d0a#diff-b84a8d65d8ed53f4794cd2db7e8ea731R48), but I've [requested they be removed until we have more
clarity around the basic lifecycle](https://github.com/opencontainers/specs/pull/231/files#r45532412).

### CODE REVIEW

**Comment by jlbutler** [comment]
I may be unintentionally reopening a can of worms, but I don't know if we want to back away from all non-blocking operations. These can be invoked with container metadata and no other state. While I feel multiple instance shared state should be left to an upper layer, I think any actions which are taken on a given instance should be owned by the container runtime (e.g. pause, exec), and therefore specified here.

**Comment by wking** [comment]
On Wed, Dec 02, 2015 at 06:00:45PM -0800, Jesse Butler wrote:

> While I feel multiple instance shared state should be left to an
> upper layer, I think any actions which are taken on a given instance
> should be owned by the container runtime (e.g. pause, exec), and
> therefore specified here.

The need for shared state comes in with your “on a given instance”.
Say you want to exec a new process in an existing container.  You pass
in the container ID, and the runtime makes the following lookups:
- container ID → process ID (via a shared state registry)
- process ID → cgroups (via /proc/{pid}/cgroup)
- process ID → namespaces (via /proc/{pid}/ns)

and then launches the new process inside those cgroups and namespaces.
You could have exec, pause, resume, and signal based only on an
existing process ID (skipping the container ID → process ID lookup,
and using the kernel and its existing permissions to manage shared
state in /proc), but that's sounding too Linux-specific to me.  And as
I pointed out in the lifecycle discussion [1](https://groups.google.com/a/opencontainers.org/d/msg/dev/frUXLljXy8Y/_sg-BidnAwAJ), the PID lookups won't
even work on Linux in post-stop hooks, which fire after that process
has been reaped.  So until we have clarity on what the state looks
like on non-Linux instances, and if/how we're going to support non-PID
cgroup/namespace lookups (and externalFds, if we decide we do need
that [2](https://groups.google.com/a/opencontainers.org/d/msg/dev/z25xQsF3pHA/ixyeTrxyFwAJ)), I think its best to leave these actions out of the
command-line API.  We can always bring them back once there's more
clarity on how they'll work.

```
 Subject: Re: Documenting container lifecycles [no-explicit-create v2]
 Message-ID: <20150928185832.GA28931@odin.tremily.us>

 Subject: Re: Drop /run/opencontainer entirely?
 Message-ID: <20150905043024.GB25638@odin.tremily.us>
```

**Comment by julz** [comment]
I think we can keep 'exec', 'pause', 'resume' etc without requiring shared state as long as we require that only the runtime which created a container should be expected to be able to manipulate it. This way the runtime can store the state information for a container wherever and however it likes without the problems of a shared directory structure that multiple runtimes have to collaborate over. It seems pretty unreasonable to expect 'runc exec' to work with a container created by a runtime other than runc anyway, so this doesn't seem much of a restriction.

Alternatively (and this is probably my favourite solution), we could add a `--state-file` parameter to the create command. This would ask the runtime to store the process state in a particular file. Other commands can then accept a similar --state-file parameter to read data needed by that command.

As a worked example, you might have:

```
funC create --bundle foo/bar --state-file /my/container/state.json
funC pause --state-file /my/container/state.json
```

**Comment by mikebrow** [comment]
He's not saying remove it permanently... He's saying we have to wait for the design discussions to land.

**Comment by julz** [comment]
And I'm saying I don't think design discussions about whether to remove the global directory preclude these commands one way or the other (although I'm not particularly against taking them off the table to get an initial version we can iterate on anyway).

**Comment by mikebrow** [comment]
From our IRC chat the other day:
"wking: mikebrow: re: dropping exec, pause, resume, and signal.  Yeah, that's just until we have some lifecycle docs around those actions.
wking: I think the command-line API should closely trail suggested lifecycle changes.  Trying to lead the way via the command line API seems like its putting the cart before the horse."

Thus this PR is to make sure this spec is behind horse. :-)

**Comment by julz** [comment]
Like I said, I don't disagree with that rationale. However the first paragraph of the PR description offers a different rationale (that these functions don't make sense without shared state). I thought it was worth clarifying (while, again, agreeing with the result - we should take these off the table for now) that these things aren't necessarily incompatible.

**Comment by mikebrow** [comment]
Yes, agreed, there are ways to implement the commands without shared state being implemented by runc, should that necessity arise.

**Comment by wking** [comment]
On Fri, Dec 04, 2015 at 09:11:30AM -0800, Mike Brown wrote:

> Yes, agreed, there are ways to implement the commands without shared
> state being implemented by runc, should that necessity arise.

There seem to be a few ideas about “shared state” floating about.
Julz is talking about the global directory [1](https://github.com/wking/oci-command-line-api/pull/3#issuecomment-162014566), and I agree that you
can implement these actions without that.  He also suggested these
could be restricted to “the runtime which created a container” [2](https://github.com/wking/oci-command-line-api/pull/3#issuecomment-162009033),
which I assume means “the executable which created the container” and
not “the process which created the container”.  When I've been saying
“shared state”, I've meant “any inter-process communication” whether
that's an OCI-specified global directory or some runtime-specific
mechanism (e.g. registering with a daemon that holds the state in
memory).  I don't see any way to support the container-ID → (cgroup /
namespace) lookups [3](https://github.com/wking/oci-command-line-api/pull/3#issuecomment-161512521) required by exec, pause, etc. without _some_
form of IPC.  But I'm happy to reword the initial PR post and commit
message to add phrasing like:

  … and after today's meeting we may be backing away from that.  Even
  if we keep a requirement for sharing state between funC invocations,
  we don't want to specify these IPC-requiring commands until we have
  more clarity on that requirement in the spec.

Does that satisfy everybody?

And @julz, should I make you a collaborator?

**Comment by mikebrow** [comment]
Looks good to me.

**Comment by wking** [comment]
On Fri, Dec 04, 2015 at 09:50:59AM -0800, Mike Brown wrote:

> Looks good to me.

Topic post updated and new commit message pushed.

**Comment by wking** [comment]
On Fri, Dec 04, 2015 at 08:17:30AM -0800, Julian Friedman wrote:

> funC create --bundle foo/bar --state-file /my/container/state.json
> funC pause --state-file /my/container/state.json

This sounds like a good approach to me.  It:
- Allows for state that has more than just the PID (vs. funC pause
  <PID>),
- Avoids ownership issues around /run/opencontainer,
- Makes it easy (with /dev/fd/3, etc. support for --state-file
  read-in) for higher-level tooling to handle state registration
  internally.  E.g. a Docker daemon could run ‘create’ without
  --state-file, use pre-start and post-stop hooks to register and
  deregister a given container, and pipe that state back into the
  later ‘pause’ invocation.
  
     Subject: removal of /run/opencontainer/containers
     Message-ID: <CAD2oYtNipt3i_C6=J4Bc-jwauo5YAvKXUqTROnPNP3vZ9+C5Vw@mail.gmail.com>

**Comment by jlbutler** [comment]
Replying late... I was thinking along the lines of @julz's reply. For posterity's sake, I find the IPC-related rationale to also be overly-specific. On Solaris, BSD and Windows, cgroups are not user-servicable parts. Our current OCI implementation for Solaris works with container ID only and has no IPC requirement.

**Comment by wking** [comment]
On Fri, Dec 04, 2015 at 10:48:39AM -0800, Jesse Butler wrote:

> Our current OCI implementation for Solaris works with container ID
> only and has no IPC requirement.

Interesting.  If you have a user-specified container ID (e.g. ‘funC
start --id hello-1’) what kernel API do you use for ‘func pause
hello-1’?  Is the container ID something that gets registered with
your kernel?

**Comment by jlbutler** [comment]
Yes, on Solaris we are creating zones under the OCI covers. Zones are in kernel and managed by a services framework built into the OS.

For context (though maybe out of date) https://en.wikipedia.org/wiki/Solaris_Containers

**Comment by wking** [comment]
On Fri, Dec 04, 2015 at 11:02:34AM -0800, Jesse Butler wrote:

> Zones are in kernel and managed by a services framework built into the OS.
> 
> For context (though maybe out of date) https://en.wikipedia.org/wiki/Solaris_Containers 

Ok, so container IDs are kernel-level entities on Solaris, and there's
no need for out-of-kernel mechanisms to share that state.  I guess
that means that the registry is global (e.g. users Alice and Bob can't
create separate containers with the same ID).  And it looks like
there's a per-host cap on the number of containers (8191) [1](https://en.wikipedia.org/wiki/Solaris_Containers#Resources_needed)?  For my
own curiosity, can you explain how permissions work?  Do you need
elevated permissions to create a container, or are unprivileged users
allowed to do some analog of [2](http://man7.org/linux/man-pages/man1/unshare.1.html)
—
    $ unshare --user --map-root-user sh

like you can on Linux since 3.8 [3](http://man7.org/linux/man-pages/man7/user_namespaces.7.html).

Does the kernel store everything needed for exec/pause/resume/signal?
E.g. Linux needs both the PID (to lookup cgroups and namespaces) and
externalFds for pause/resume [4,5].  If so, I'll amend the commit
message and PR topic to soften the IPC requirement to a “possible IPC
requirement”, and I'll point out Solaris as an example of a system
where the kernel handles the state registration.

Anyway, if you have a kernel-level container ID registry that tracks
everything you need, it seems unnecessary to glom on an additional
state-sharing mechanism.  I'm not sure how to square that with Julz's
--state-file suggetion [6,7].  Would we add a special-case --id
argument to exec/pause/resume/signal that only works on some runtimes
(e.g. those where the kernel or runtime provide a built-in container
registry)?  This is all useful stuff that's worth pushing back into
the wider state-sharing discussion [8](https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/q6TYqVZOcX8).

```
 Subject: Re: Drop /run/opencontainer entirely?
 Message-ID: <20150905043024.GB25638@odin.tremily.us>



 Subject: removal of /run/opencontainer/containers
 Message-ID: <CAD2oYtNipt3i_C6=J4Bc-jwauo5YAvKXUqTROnPNP3vZ9+C5Vw@mail.gmail.com>
```

**Comment by jlbutler** [comment]
Right, there is no need for out-of-kernel entities to share state, but state is available via the zones management framework, and via SMF. (If you're not familiar with SMF, it's the thing that systemd was inspired by... as far as I can tell, anyhow).

The kernel state would have all the data required for these operations, yes. For example, our 'exec' implementation simply invokes the cmd on the container via code which mirrors the zlogin(1) utility (which effectively exec's from the host into the guest).

You are correct that we don't need a state file, but I don't know that we'd required an --id either. We pass a new config.json file in our current implementation, and we use the optional 'hostname' element to identify the container. These are also unique on a per-kernel instance basis. I'm in support of having an optional --state-file if others find it useful, and it seems it would be necessary for Linux (and maybe other OS's down the road).

Management of zones requires privilege, but not necessarily superuser. It is simple in Solaris to provide role-based access control to various operations without granting full superuser privilege. So any given user can be granted full administrative rights to zones (and runz, docker, etc).

I agree this is useful, and I think we'll continue to find beneficial difference as we compare Linux and Solaris containers.

**Comment by wking** [comment]
On Fri, Dec 04, 2015 at 12:53:38PM -0800, Jesse Butler wrote:

> You are correct that we don't need a state file, but I don't know
> that we'd required an --id either. We pass a new config.json file in
> our current implementation, and we use the optional 'hostname'
> element to identify the container.

config.json's ‘hostname’ isn't about “which host do you want to
connect to”, it's about “what hostname should we set when creating a
new container” (see opencontainers/specs#214).

You also said (but GitHub thinks this was part of my email signature, so I've removed the blockquote Markdown):

  These are also unique on a per-kernel instance basis. I'm in support
  of having an optional --state-file if others find it useful, and it
  seems it would be necessary for Linux (and maybe other OS's down the
  road).

But I think
optional --state-file would be tricky.  For example, how would you
write a conformance testing suite when some runtimes have an ‘exec’
that only supports --state-file and others have an ‘exec’ that only
supports --id?  If runtime-internal (or kernel-level) container ID
registration is optional (which I think makes sense on Linux [1](https://github.com/wking/oci-command-line-api/pull/3#issuecomment-162041009)),
then how would you feel about _requiring_ --state-file support in all
runtimes?  For Solaris, the only thing you'd need from the state JSON
was the container ID, but that doesn't seem like it would be too hard
to handle.  You could have an optional --id for folks that didn't want
to send in state JSON when pausing a container (or whatever), but the
runtime-conformance tester could rely on --state-file being supported.

**Comment by mikebrow** [comment]
Agree... 
Additionally I think the id should be more of an abstract thing and unique per instance of a container... not a file name.  Though I could see the id mapping to a handle (file, url, etc..)

**Comment by wking** [comment]
I've pushed some Solaris wording to the commit message (with 98f0fcb →
9fa0f03).  Can folks look that over and give LGTMs on 9fa0f03 (or
suggest additional adjustments)?  I'll restart the two-workday clock
on this PR now to make sure folks have time to look over the revised
motivation before this lands.

**Comment by jlbutler** [comment]
Well, wether the intent of hostname is to name an instance or not, it maps to our container uuid, so as an implementation detail, it works. I'm good with pulling these for now, and appreciate your additional context for !linux. 

Edit: Bug in my statement. We use container id as the hostname. So, the unique identifier is indeed the container id.

**Comment by wking** [comment]
Added a Signed-off-by with 9fa0f03 → 0fb3aa7.

**Comment by wking** [comment]
Rebased onto master with 0fb3aa7 → 61e38ac to resolve trivial
conflicts with #2 and its reference-style links (keeping the new
links).

**Comment by julz** [comment]
lgtm

**Comment by wking** [comment]
On Mon, Dec 07, 2015 at 11:05:42AM -0800, Julian Friedman wrote:

> lgtm  

Merged, with Reviewed-by's for Julz^, Mike [1](https://github.com/wking/oci-command-line-api/pull/3#issuecomment-162033824), and Jesse [2](https://github.com/wking/oci-command-line-api/commit/9fa0f0317509ddbd9139c90499beb3e159cc9c20#commitcomment-14798634).  The
only other changes since Mike and Jesse's LGTMs are my Signed-off-by
[3](https://github.com/wking/oci-command-line-api/pull/3#issuecomment-162145245) and a rebase [4](https://github.com/wking/oci-command-line-api/pull/3#issuecomment-162234050).

**Pull request merged**
